#!/bin/bash

cd ${HOME}

display -window root .wallpaper.png

sudo rm -r -f /usr/share/{doc,gtk-doc,help}

rm -f    -- .cache .thumbnails
rm -f -r -- .cache .thumbnails

ln -s -f -n -- /tmp/${USER}/cache            ${HOME}/.cache
ln -s -f -n -- /tmp/${USER}/cache/thumbnails ${HOME}/.thumbnails

mkdir -p -- IMPRESSO IMPRIMIR /tmp/${USER}/cache/thumbnails

chmod 0700 /tmp/${USER}

sudo chmod 0777 /dev/input/*

#sudo hdparm -B 240 /dev/sda
#sudo hdparm -S 120 /dev/sda

xset s off
xset +dpms

sudo tail /proc/sys/vm/dirty_background_bytes <<< 268435456
sudo tail /proc/sys/vm/dirty_writeback_centisecs <<< 1000
sudo tail /proc/sys/vm/dirty_expire_centisecs <<< 1000

sudo tail /proc/sys/net/ipv4/neigh/default/gc_interval <<< 120
sudo tail /proc/sys/net/ipv4/route/gc_interval <<< 180
sudo tail /proc/sys/net/ipv4/tcp_timestamps <<< 0
sudo tail /proc/sys/net/ipv4/tcp_congestion_control <<< scalable
sudo tail /proc/sys/net/ipv4/icmp_echo_ignore_all <<< 1
sudo tail /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts <<< 1
sudo tail /proc/sys/net/ipv4/tcp_syn_retries <<< 3
sudo tail /proc/sys/net/ipv4/tcp_synack_retries <<< 3
sudo tail /proc/sys/net/ipv4/tcp_retries2 <<< 3
sudo tail /proc/sys/net/ipv4/tcp_fin_timeout <<< 8
sudo tail /proc/sys/net/ipv4/tcp_orphan_retries <<< 2

#xrandr \
#--output HDMI-0 --off \
#--output DVI-0 --mode 2560x1080 \
#--output DisplayPort-0 --mode 1920x1080 --rate 144 --left-of DVI-0

setxkbmap -model abnt2 -layout br -variant abnt2

tint2 &

sleep 0.5

parcellite &

pidgin &
