#!/bin/bash

cd ${HOME}

sudo rm -r -f /usr/share/{doc,gtk-doc,help}

rm -f    -- .cache .thumbnails
rm -f -r -- .cache .thumbnails

ln -s -f -n -- /tmp/${USER}/cache            ${HOME}/.cache
ln -s -f -n -- /tmp/${USER}/cache/thumbnails ${HOME}/.thumbnails

mkdir -p -- IMPRESSOS IMPRIMIR /tmp/${USER}/cache/thumbnails

chmod 0700 /tmp/${USER}

sudo chmod 0777 /dev/input/*

#sudo hdparm -B 240 /dev/sda
#sudo hdparm -S 120 /dev/sda

xset s off
xset +dpms

display -window root .wallpaper.png

sudo bash -c "echo 268435456 > /proc/sys/vm/dirty_background_bytes"
sudo bash -c "echo 1000 > /proc/sys/vm/dirty_writeback_centisecs"
sudo bash -c "echo 1000 > /proc/sys/vm/dirty_expire_centisecs"

sudo bash -c "echo 120 > /proc/sys/net/ipv4/neigh/default/gc_interval"
sudo bash -c "echo 180 > /proc/sys/net/ipv4/route/gc_interval"

sudo bash -c "echo 0 > /proc/sys/net/ipv4/tcp_timestamps"

sudo bash -c "echo scalable > /proc/sys/net/ipv4/tcp_congestion_control"

sudo bash -c "echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_all"
sudo bash -c "echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts"

#  The maximum number of times initial SYNs for an active TCP connection attempt will be retransmitted.
sudo bash -c "echo 3 > /proc/sys/net/ipv4/tcp_syn_retries"

# The maximum number of times a SYN/ACK segment for a passive TCP connection will be retransmitted.
sudo bash -c "echo 3 > /proc/sys/net/ipv4/tcp_synack_retries"

# The maximum number of times a TCP packet is retransmitted in established state before giving up.
# The default value is 15, which corresponds to a duration of approximately between 13 to 30 minutes, depending on the retransmission timeout.
sudo bash -c "echo 3 > /proc/sys/net/ipv4/tcp_retries2"

# This specifies how many seconds to wait for a final FIN packet before the socket is forcibly closed.
# This is strictly a violation of the TCP specification, but required to prevent denial-of-service attacks.
sudo bash -c "echo 8 > /proc/sys/net/ipv4/tcp_fin_timeout"

# The maximum number of attempts made to probe the other end of a connection which has been closed by our end.
sudo bash -c "echo 2 > /proc/sys/net/ipv4/tcp_orphan_retries"

#xrandr \
#--output HDMI-0 --off \
#--output DVI-0 --mode 2560x1080 \
#--output DisplayPort-0 --mode 1920x1080 --rate 144 --left-of DVI-0

setxkbmap -model abnt2 -layout br -variant abnt2
tint2 &
sleep 0.5
parcellite &
pidgin &
