#!/bin/bash

cd ${HOME}

display -window root .wallpaper.png

sudo rm -r -f /usr/share/{doc,gtk-doc,help}

rm -f    -- .cache .thumbnails
rm -f -r -- .cache .thumbnails

ln -s -f -n -- /tmp/${USER}/cache            ${HOME}/.cache
ln -s -f -n -- /tmp/${USER}/cache/thumbnails ${HOME}/.thumbnails

mkdir -p -- IMPRESSO IMPRIMIR /tmp/${USER}/cache/thumbnails

chmod 0700 /tmp/${USER}

sudo chmod 0777 /dev/input/*

#sudo hdparm -B 240 /dev/sda
#sudo hdparm -S 120 /dev/sda

xset s off
xset +dpms

sudo tail /proc/sys/vm/dirty_background_bytes <<< 268435456
sudo tail /proc/sys/vm/dirty_writeback_centisecs <<< 1000
sudo tail /proc/sys/vm/dirty_expire_centisecs <<< 1000

sudo tail /proc/sys/net/ipv4/neigh/default/gc_interval <<< 120
sudo tail /proc/sys/net/ipv4/route/gc_interval <<< 180
sudo tail /proc/sys/net/ipv4/tcp_timestamps <<< 0
sudo tail /proc/sys/net/ipv4/tcp_congestion_control <<< scalable
sudo tail /proc/sys/net/ipv4/icmp_echo_ignore_all <<< 1
sudo tail /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts <<< 1
sudo tail /proc/sys/net/ipv4/tcp_syn_retries <<< 3
sudo tail /proc/sys/net/ipv4/tcp_synack_retries <<< 3
sudo tail /proc/sys/net/ipv4/tcp_retries2 <<< 3
sudo tail /proc/sys/net/ipv4/tcp_fin_timeout <<< 8
sudo tail /proc/sys/net/ipv4/tcp_orphan_retries <<< 2

#xrandr \
#--output HDMI-0 --off \
#--output DVI-0 --mode 2560x1080 \
#--output DisplayPort-0 --mode 1920x1080 --rate 144 --left-of DVI-0

setxkbmap -model abnt2 -layout br -variant abnt2

tint2 &

sleep 0.5

parcellite &

pidgin &

######
sudo tail /proc/sys/net/ipv4/ip_forward <<< 1
sudo tail /proc/sys/net/ipv6/conf/default/forwarding <<< 1
sudo tail /proc/sys/net/ipv6/conf/enp1s0/forwarding <<< 1

sudo ip link set dev enp1s0 up

sudo ip addr add 192.168.1.0/24 dev enp1s0
sudo ip addr add 172.23.0.200/24 dev enp1s0

sudo openvpn --config /etc/coren/openvpn.ovpn --auth-user-pass /etc/coren/auth &

sudo pppd plugin /usr/lib/rp-pppoe/rp-pppoe.so nic-enp1s0 rp_pppoe_service velox noipdefault noauth default-asyncmap defaultroute hide-password nodetach mtu 1492 mru 1492 noaccomp nodeflate nopcomp novj novjccomp user 2422370921@oi.com.br lcp-echo-interval 20 lcp-echo-failure 3 &

#iptables -t nat -A PREROUTING -p tcp --dport 9100 -j DNAT --to-destination 172.23.0.2:9100
#iptables -t nat -A PREROUTING -p tcp --dport 8000 -j DNAT --to-destination 172.23.0.2:80
sudo iptables -t nat -A POSTROUTING -o ppp0 -s 172.23.0.0/24 -j MASQUERADE
#iptables -t nat -A POSTROUTING -o enp1s0 ! -s 192.168.1.0/24 -j MASQUERADE

# MARQUERADE VPN
#########
